const app=document.querySelector('#app');
let csvText='', fileName='', vehicle='Parrot Anafi', notes='Investigate abnormal motor shutdowns, battery events and flight-control anomalies.', result=null, loading=false, error='', replayState='idle', replayResult=null, replayError='', systemStatus='checking', investigationId=createInvestigationId(), investigationStatus='OPEN';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function render(){
  app.innerHTML=`<div class="app-shell"><nav><div class="brand"><div class="brandmark">◉</div><span>AeroSage</span><em>AI</em></div><div class="nav-badges"><span>NEBIUS</span><span>NVIDIA NEMOTRON</span><span class="status-badge ${systemStatus}">● ${String(systemStatus).toUpperCase()}</span></div></nav><main>
  <section class="hero"><div class="eyebrow">✣ AI TELEMETRY INCIDENT INVESTIGATOR</div><h1>Turn machine logs into<br><span>evidence you can act on.</span></h1><p>AeroSage profiles telemetry, detects anomalies, reconstructs incident sequences and enriches the evidence with Nemotron and Tavily without allowing provider failures to erase the forensic report.</p></section>
  ${renderWorkspace()}<section class="use-cases"><div><span>01</span><strong>Post-incident investigation</strong><p>Turn raw flight logs into a traceable incident package.</p></div><div><span>02</span><strong>Engineering triage</strong><p>Separate measured signals from plausible but unsupported causes.</p></div><div><span>03</span><strong>Audit-ready handoff</strong><p>Export evidence, decisions and deterministic replay fingerprints.</p></div></section>
  <section class="workspace"><div class="panel upload-panel"><div class="panel-head"><div><span class="step">01</span><h2>Evidence intake</h2></div><span>♢</span></div>
  <label class="dropzone" id="dropzone"><input id="fileInput" type="file" accept=".csv,text/csv" aria-label="Telemetry CSV file"><strong>${fileName?esc(fileName):'Drop a telemetry CSV'}</strong><small>${fileName?`${(csvText.length/1024).toFixed(1)} KB loaded locally`:'CSV · max 4 MB for this MVP'}</small></label>
  <button id="demoBtn" class="ghost">Load real sanitized drone incident demo ›</button>
  ${!csvText?`<div class="value-strip"><div><span>INPUT</span><strong>Raw telemetry CSV</strong><small>Vendor-agnostic intake</small></div><div><span>PROCESS</span><strong>Evidence → hypotheses</strong><small>Deterministic rules + AI</small></div><div><span>OUTPUT</span><strong>Forensic report</strong><small>Evidence, timeline, actions</small></div></div>`:`<div class="file-summary"><div><span>FILE READY</span><strong>${esc(fileName)}</strong><small>${(csvText.length/1024).toFixed(1)} KB · locally loaded</small></div><span class="ready-dot">● READY</span></div>`}
  <div class="field-grid"><label>Vehicle / system<input id="vehicle" value="${esc(vehicle)}"></label><label>Investigation goal<textarea id="notes" rows="3">${esc(notes)}</textarea></label></div>
  <button id="runBtn" class="primary" ${!csvText||loading?'disabled':''}>${loading?'⌁ Investigating telemetry…':'✣ Run forensic analysis'}</button>${error?`<div class="error">ⓧ ${esc(error)}</div>`:''}</div>
  <div class="panel process-panel"><div class="panel-head"><div><span class="step">02</span><h2>Investigation pipeline</h2></div></div><div class="pipeline">
  ${proc('◔','Schema profiler','Discovers numeric signals, ranges and missingness without assuming one drone vendor.')}${proc('△','Anomaly engine','Flags robust statistical outliers plus domain safety events such as cut-outs and critical battery states.')}${proc('✣','Nemotron reasoning','Ranks competing hypotheses from evidence rather than inventing a single cause.')}${proc('♢','Evidence guardrails','Post-validates every AI hypothesis against target-event telemetry before it can be ranked.')}${proc('⌕','Technical grounding','Uses Tavily to compare the incident against manuals and documented failure modes when available.')}</div><div class="privacy"><span>♢</span><div><strong>Evidence-first by design</strong><span>The baseline report is returned before any external AI call.</span></div></div>
  <div class="output-preview"><span class="preview-label">YOU GET</span><div><b>Risk level</b><b>Ranked causes</b><b>Evidence ledger</b><b>Timeline</b><b>Next actions</b><b>Replay fingerprint</b></div></div></div></section>
  ${result?renderResult(result):''}<footer><span>AeroSage · Nebius × NVIDIA Global AI Hackathon 2026</span><span>Standalone zero-dependency MVP · MIT</span></footer></main></div>`;
  bind();
}
function proc(icon,title,text){return `<div class="process"><div>${icon}</div><section><strong>${title}</strong><p>${text}</p></section></div>`}
function renderResult(r){const score=Math.round((r.confidence||0)*100);const status=r.mode==='live'?`Live Nemotron analysis · ${esc(r.model||'')}${r.web_status==='live'?' · Tavily grounded':''} · evidence-checked`:r.mode==='baseline'?'Evidence-first report ready · enriching with Nemotron + Tavily…':`Evidence-first report · Nemotron fallback${r.web_status==='live'?' · Tavily grounded':''}`;return `<section class="results"><div class="section-title"><span class="step">03</span><div><h2>Incident report</h2><p>${status}</p>${r.ai_note?`<p class="query">Nemotron note: ${esc(r.ai_note)}</p>`:''}</div></div><div class="investigation-meta"><span class="investigation-id">${esc(investigationId)}</span><select id="statusSelect" aria-label="Investigation status"><option ${investigationStatus==='OPEN'?'selected':''}>OPEN</option><option ${investigationStatus==='INVESTIGATING'?'selected':''}>INVESTIGATING</option><option ${investigationStatus==='RESOLVED'?'selected':''}>RESOLVED</option></select></div><div class="report-toolbar" id="reportActions"><button id="copyReport" class="tool-btn">⧉ Copy report</button><button id="downloadReport" class="tool-btn">↓ Download JSON</button><button id="downloadEvidence" class="tool-btn">↓ Evidence CSV</button><button id="downloadBundle" class="tool-btn">⇩ Evidence bundle</button><button id="shareInvestigation" class="tool-btn">↗ Share investigation</button><button id="newInvestigation" class="tool-btn subtle">＋ New investigation</button></div>
<div class="summary-grid"><div class="panel verdict-card"><div class="verdict-top"><span class="risk ${esc(r.risk_level)}">${esc(r.risk_level)} risk</span><div class="confidence"><strong>${score}%</strong><span>confidence</span></div></div><h3>Investigator conclusion</h3><p>${esc(r.executive_summary)}</p><div class="metric-row">${metric(r.metrics?.rows,'records')}${metric(r.metrics?.numeric_columns,'signals')}${metric(r.metrics?.anomaly_count,'anomalies')}${metric(r.metrics?.incident_rows,'incident rows')}</div></div>
<div class="panel causes-card"><h3>Ranked hypotheses</h3><div class="causes">${(r.likely_causes||[]).map((c,i)=>`<div class="cause"><div class="cause-row"><span>${i+1}</span><strong>${esc(c.cause)}</strong><b>${Math.round((c.confidence||0)*100)}%</b></div><p>${esc(c.why)}</p><div class="bar"><i style="width:${Math.round((c.confidence||0)*100)}%"></i></div></div>`).join('')}</div></div></div>
<div class="detail-grid"><div class="panel"><h3>Evidence ledger</h3><div class="evidence-list">${(r.evidence||[]).map(e=>`<div class="evidence"><span class="dot ${esc(e.weight)}"></span><div><strong>${esc(e.signal)}</strong><p>${esc(e.observation)}</p></div><em>${esc(e.weight)}</em></div>`).join('')}</div></div><div class="panel"><h3>Reconstructed sequence</h3><div class="timeline">${(r.timeline||[]).map((t,i)=>`<div class="timeline-item"><span>${String(i+1).padStart(2,'0')}</span><div><strong>${esc(t.phase)}</strong><p>${esc(t.finding)}</p></div></div>`).join('')}</div></div></div>
<div class="panel actions"><h3>Recommended next actions</h3><div class="action-grid">${(r.next_actions||[]).map(a=>`<div><span>✓</span><span>${esc(a)}</span></div>`).join('')}</div></div>
<div class="panel action-gate"><div class="gate-head"><div><span class="trace-label">ACTION GATE</span><h3>Human review required</h3><p class="query">AeroSage recommends and documents actions; it never autonomously actuates the system.</p></div><span class="gate-badge">REVIEW_ONLY</span></div><div class="gate-summary"><div><span>CONTROL</span><strong>No automatic actuation</strong></div><div><span>AUTHORITY</span><strong>Human operator</strong></div><div><span>TRACEABILITY</span><strong>Evidence + replay</strong></div></div></div>${renderProvenance(r)}
${renderDecisionLedger(r)}
${renderEvidenceManifest(r)}
${renderInvestigationTrace(r)}
${r.evidence_guardrails?.length?`<div class="panel"><h3>Evidence guardrails</h3><p class="query">AI proposes · telemetry decides${r.guardrail_filtered?` · ${r.guardrail_filtered} unsupported claim(s) filtered`:''}</p><div class="evidence-list">${r.evidence_guardrails.map(g=>`<div class="evidence"><span class="dot high"></span><div><strong>Constraint</strong><p>${esc(g)}</p></div><em>checked</em></div>`).join('')}</div></div>`:''}
${r.web_grounding?.sources?.length?`<div class="panel grounding"><h3>Technical grounding</h3><p class="query">Search: “${esc(r.web_grounding.query)}”</p><div class="sources">${r.web_grounding.sources.map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noreferrer"><span>⌕</span><span>${esc(s.title)}</span><span>›</span></a>`).join('')}</div></div>`:''}</section>`}
function renderInvestigationTrace(r){
  const probe=r.validation_probe;
  const traces=r.investigation_trace||[];
  if(!probe&&!traces.length)return '';
  const probeHtml=probe?`<div class="trace-case"><div class="trace-case-head"><div><span class="trace-label">ADVERSARIAL CONTROL</span><strong>Reproducible contradiction test</strong></div><span class="trace-verdict rejected">${esc(probe.verdict)}</span></div><div class="trace-flow">${traceStep('1','Telemetry evidence',probe.telemetry_evidence)}${traceStep('2','Nemotron hypothesis',`${probe.hypothesis} · ${Math.round(probe.proposed_confidence*100)}%`)}${traceStep('3','Deterministic rule',probe.rule)}${traceStep('4','Verdict',probe.reason,'rejected')}</div></div>`:'';
  const actualHtml=traces.length?`<details class="trace-details"><summary>Inspect ${traces.length} live hypothesis decision${traces.length===1?'':'s'}</summary><div class="trace-list">${traces.map(t=>`<div class="trace-row"><div><strong>${esc(t.hypothesis)}</strong><span>${t.proposed_confidence===null?'deterministic baseline restored':`${Math.round((t.proposed_confidence||0)*100)}% proposed${t.verdict==='CAPPED'?` → ${Math.round((t.final_confidence||0)*100)}% final`:''}`}</span></div><p>${esc(t.telemetry_evidence)}</p><span class="trace-verdict ${String(t.verdict).toLowerCase()}">${esc(t.verdict)}</span></div>`).join('')}</div></details>`:'';
  return `<div class="panel trace-panel"><div class="trace-title"><div><h3>Investigation trace</h3><p class="query">Telemetry evidence → Nemotron hypothesis → deterministic rule → verdict</p></div><span class="trust-badge">MODEL NEVER SELF-VALIDATES</span></div>${probeHtml}${actualHtml}</div>`;
}
function traceStep(n,title,text,state=''){return `<div class="trace-step ${state}"><span>${n}</span><div><strong>${esc(title)}</strong><p>${esc(text)}</p></div></div>`}
function renderDecisionLedger(r){
  const ledger=r.decision_ledger;
  if(!ledger?.entries?.length)return '';
  const summary=ledger.summary||{};
  const entries=ledger.entries.map(entry=>`<article class="decision-entry"><div class="decision-head"><div><span>${esc(entry.decision_id)} · ${esc(entry.domain)} · ${esc(entry.proposal_source)}</span><strong>${esc(entry.hypothesis)}</strong></div><span class="trace-verdict ${String(entry.verdict).toLowerCase()}">${esc(entry.verdict)}</span></div><div class="decision-columns"><div><span class="ledger-label">TELEMETRY INPUTS</span><div class="ledger-inputs">${(entry.telemetry_inputs||[]).map(input=>`<code>${esc(input.field)} = ${esc((input.samples||[]).map(sample=>`${sample.value} @ row ${sample.row_index}`).join(', '))}</code>`).join('')||'<code>No domain-specific field available</code>'}</div></div><div><span class="ledger-label">RULE VOTES</span><div class="rule-votes">${(entry.rule_votes||[]).map(vote=>`<div><b>${esc(vote.vote)}</b><span>${esc(vote.rule_id)}</span><p>${esc(vote.rationale)}</p></div>`).join('')}</div></div></div><p class="decision-resolution">${esc(entry.resolution)}</p>${entry.final_rank?`<span class="final-rank">FINAL RANK #${entry.final_rank}</span>`:''}</article>`).join('');
  const suppressed=(ledger.suppressed_competitors||[]).length?`<div class="suppressed-list"><span class="ledger-label">SUPPRESSED OR LIMITED COMPETITORS</span>${ledger.suppressed_competitors.map(item=>`<p><b>${esc(item.verdict)}</b> ${esc(item.hypothesis)} — ${esc(item.reason)}</p>`).join('')}</div>`:'';
  return `<div class="panel ledger-panel"><div class="trace-title"><div><h3>Decision ledger</h3><p class="query">Every proposal, measured input, rule vote and suppression reason</p></div><span class="trust-badge">${Number(summary.accepted||0)} ACCEPTED · ${Number(summary.capped||0)} CAPPED · ${Number(summary.rejected||0)} REJECTED</span></div><div class="ledger-meta"><span>${esc(ledger.schema)}</span><span>${esc(ledger.ruleset)}</span><span>Rows ${esc((ledger.target_rows||[]).join(', '))}</span></div><div class="decision-list">${entries}</div>${suppressed}</div>`;
}
function renderProvenance(r){
  const p=r.evidence_provenance;
  if(!p)return '';
  const perf=r.analysis_performance;
  return `<div class="panel provenance-panel"><div class="trace-title"><div><h3>Why the model cannot manufacture evidence</h3><p class="query">Measured values remain outside the model's authority</p></div><span class="trust-badge">READ-ONLY EVIDENCE</span></div><div class="provenance-flow"><div><span>01</span><strong>CSV telemetry</strong><p>Rows ${esc((p.target_rows||[]).join(', '))} selected from the uploaded file.</p></div><div><span>02</span><strong>Deterministic preprocessing</strong><p>${(p.authoritative_signals||[]).length} authoritative signals extracted without an LLM.</p></div><div><span>03</span><strong>Nemotron proposes</strong><p>The model reads the packet but cannot create or modify its measurements.</p></div><div><span>04</span><strong>Rules adjudicate</strong><p>Post-inference guardrails accept, cap or reject each hypothesis.</p></div></div><div class="signal-chips">${(p.authoritative_signals||[]).map(s=>`<span><b>${esc(s.field)}</b> ${esc(s.values.join(', '))}</span>`).join('')}</div>${perf?`<p class="benchmark-line">This run: ${Number(perf.rows_processed||0)} rows · ${Number(perf.numeric_signals_profiled||0)} numeric signals · ${Number(perf.elapsed_ms||0).toFixed(1)} ms server analysis</p>`:''}</div>`;
}
function renderEvidenceManifest(r){
  const m=r.evidence_manifest;
  if(!m)return '';
  const proof=r.deterministic_replay;
  const replayStatus=replayState==='running'?'<div class="replay-status running">Recomputing the deterministic path…</div>':replayError?`<div class="replay-status mismatch">${esc(replayError)}</div>`:replayResult?`<div class="replay-status ${replayResult.exact_match?'match':'mismatch'}"><strong>${esc(replayResult.status)}</strong><span>${esc(replayResult.statement)}</span><code>${esc(replayResult.actual_verdict_sha256||'')}</code></div>`:'';
  const replayBox=proof?`<div class="replay-box"><div><span>DETERMINISTIC VERDICT SHA-256</span><code>${esc(proof.verdict_sha256)}</code><p>Same CSV bytes + same ${esc(proof.guardrail_ruleset)} policy must produce this exact fingerprint without invoking Nemotron or Tavily.</p></div><button id="replayBtn" class="replay-btn" ${replayState==='running'?'disabled':''}>${replayState==='running'?'Replaying…':'↻ Replay this incident'}</button>${replayStatus}</div>`:'';
  return `<div class="panel manifest-panel"><div class="trace-title"><div><h3>Evidence manifest</h3><p class="query">Tamper-evident identity for this investigation run</p></div><span class="trust-badge">SHA-256 VERIFIED</span></div><div class="manifest-grid"><div><span>CSV SHA-256</span><code>${esc(m.csv_sha256)}</code></div><div><span>Manifest SHA-256</span><code>${esc(m.manifest_sha256)}</code></div><div><span>Nemotron model</span><code>${esc(m.nemotron_model)}</code></div><div><span>Guardrail ruleset</span><code>${esc(m.guardrail_ruleset)}</code></div><div><span>Generated at</span><code>${esc(m.generated_at)}</code></div></div>${replayBox}<div class="reproduce-box"><span>CLI REPRODUCTION</span><code>node scripts/reproduce-magnetic-verdict.mjs</code><p>Replays the committed CSV through the production deterministic path and exits non-zero if the 88% magnetic claim is not rejected.</p></div></div>`;
}
function reportPlainText(r){
  const lines=['AEROSAGE INCIDENT REPORT','','Vehicle: '+(vehicle||'Unknown'),'Source file: '+(fileName||'Unknown'),'Risk: '+(r.risk_level||'unknown'),'Confidence: '+Math.round((r.confidence||0)*100)+'%','','CONCLUSION',r.executive_summary||'','','HYPOTHESES',...(r.likely_causes||[]).map((c,i)=>(i+1)+'. '+c.cause+' — '+Math.round((c.confidence||0)*100)+'% — '+c.why),'','EVIDENCE',...(r.evidence||[]).map(e=>'['+e.weight+'] '+e.signal+': '+e.observation),'','NEXT ACTIONS',...(r.next_actions||[]).map((a,i)=>(i+1)+'. '+a)];
  return lines.join('\n');
}
function downloadText(name,text,type='text/plain'){
  const blob=new Blob([text],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);
}
function evidenceCsv(r){
  const rows=[['weight','signal','observation']];(r.evidence||[]).forEach(e=>rows.push([e.weight,e.signal,e.observation]));
  return rows.map(row=>row.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\n');
}
function metric(v,l){return `<div class="metric"><strong>${Number(v||0)}</strong><span>${l}</span></div>`}
function bind(){
  document.querySelector('#demoBtn')?.addEventListener('click',async()=>{error='';const r=await fetch('/demo/anafi_incidents_sanitized.csv');csvText=await r.text();fileName='anafi_incidents_sanitized.csv';vehicle='Parrot Anafi';notes='Investigate the motor cut-out sequence and distinguish it from battery, radio-link, GPS, or magnetic causes.';result=null;resetReplay();render()});
  const input=document.querySelector('#fileInput'); const dz=document.querySelector('#dropzone'); input?.addEventListener('change',e=>{const f=e.target.files?.[0];if(f)loadFile(f)}); ['dragenter','dragover'].forEach(ev=>dz?.addEventListener(ev,e=>{e.preventDefault();dz.classList.add('dragging')})); ['dragleave','drop'].forEach(ev=>dz?.addEventListener(ev,e=>{e.preventDefault();dz.classList.remove('dragging')})); dz?.addEventListener('drop',e=>{const f=e.dataTransfer?.files?.[0];if(f)loadFile(f)});
  document.querySelector('#vehicle')?.addEventListener('input',e=>vehicle=e.target.value);document.querySelector('#notes')?.addEventListener('input',e=>notes=e.target.value);
  document.querySelector('#runBtn')?.addEventListener('click',analyze);
  document.querySelector('#statusSelect')?.addEventListener('change',e=>{investigationStatus=e.target.value;saveHistoryEntry();void saveServerEntry();render()});
  document.querySelectorAll('[data-history-id]').forEach(el=>el.addEventListener('click',()=>loadHistoryEntry(el.dataset.historyId)));
  document.querySelector('#clearHistory')?.addEventListener('click',clearHistory);
  document.querySelector('#compareBtn')?.addEventListener('click',renderComparison);
  document.querySelector('#shareInvestigation')?.addEventListener('click',shareInvestigation);
  document.querySelector('#replayBtn')?.addEventListener('click',replayIncident);
  document.querySelector('#copyReport')?.addEventListener('click',async()=>{if(!result)return;try{await navigator.clipboard.writeText(reportPlainText(result));const b=document.querySelector('#copyReport');if(b){b.textContent='✓ Copied';setTimeout(()=>b.textContent='⧉ Copy report',1400)}}catch{error='Clipboard access was blocked by the browser.';render()}});
  document.querySelector('#downloadReport')?.addEventListener('click',()=>{if(result)downloadText('aerosage-report-'+Date.now()+'.json',JSON.stringify({vehicle,fileName,report:result},null,2),'application/json')});
  document.querySelector('#downloadEvidence')?.addEventListener('click',()=>{if(result)downloadText('aerosage-evidence-'+Date.now()+'.csv',evidenceCsv(result),'text/csv')});
  document.querySelector('#downloadBundle')?.addEventListener('click',()=>{if(!result)return;const bundle={schema:'aerosage-evidence-bundle-v1',investigation_id:investigationId,vehicle,source_file:fileName,exported_at:new Date().toISOString(),evidence_manifest:result.evidence_manifest||null,evidence_provenance:result.evidence_provenance||null,decision_ledger:result.decision_ledger||null,investigation_trace:result.investigation_trace||[],deterministic_replay:result.deterministic_replay||null,action_policy:result.action_policy||null,guardrails:result.evidence_guardrails||[],grounding_sources:result.web_grounding?.sources||[]};downloadText('aerosage-evidence-bundle.json',JSON.stringify(bundle,null,2),'application/json')});
  document.querySelector('#newInvestigation')?.addEventListener('click',()=>{csvText='';fileName='';result=null;error='';resetReplay();investigationId=createInvestigationId();investigationStatus='OPEN';window.scrollTo({top:0,behavior:'smooth'});render()});
}
async function parseResponse(res){const raw=await res.text();try{return JSON.parse(raw)}catch{return {error:`Backend returned unreadable data (HTTP ${res.status}).`}}}
async function call(action,extra={}){const params=new URLSearchParams({action,vehicle,notes,...extra});const res=await fetch(`/api/analyze?${params}`,{method:'POST',headers:{'content-type':'text/csv; charset=utf-8'},body:csvText});const data=await parseResponse(res);if(!res.ok||data.error)throw new Error(data.error||`HTTP ${res.status}`);return data}
async function loadFile(f){if(f.size>4_000_000){error='For this MVP, use a CSV under 4 MB.';render();return}if(!/\.csv$/i.test(f.name)){error='Please choose a CSV telemetry file.';render();return}csvText=await f.text();fileName=f.name;result=null;error='';resetReplay();render()}
function resetReplay(){replayState='idle';replayResult=null;replayError=''}
async function replayIncident(){const expected=result?.deterministic_replay?.verdict_sha256;if(!csvText||!expected||replayState==='running')return;replayState='running';replayResult=null;replayError='';render();try{const replay=await call('replay',{expected});replayResult=replay.replay_verification||null;if(!replayResult)throw new Error('Replay returned no verification record.');replayState=replayResult.exact_match?'match':'mismatch'}catch(e){replayState='error';replayError=e?.message||'Replay failed'}render()}
async function analyze(){if(!csvText||loading)return;loading=true;error='';result=null;resetReplay();investigationStatus='INVESTIGATING';render();try{result=await call('base');saveHistoryEntry();void saveServerEntry();loading=false;render();try{const enriched=await call('enrich');if(enriched&&!enriched.error)result=enriched}catch{}saveHistoryEntry();void saveServerEntry();render()}catch(e){loading=false;error=e?.message||'Analysis failed';render()}}
render();

function createInvestigationId(){const d=new Date();const stamp=d.toISOString().slice(0,10).replaceAll('-','');const rnd=Math.random().toString(36).slice(2,10).toUpperCase();return 'AS-'+stamp+'-'+rnd}
function historyKey(){return 'aerosage.investigations.v1'}
function getHistory(){try{return JSON.parse(localStorage.getItem(historyKey())||'[]')}catch{return[]}}
function saveHistoryEntry(){if(!result)return;const h=getHistory();const entry={id:investigationId,createdAt:new Date().toISOString(),vehicle,fileName,risk:result.risk_level||'unknown',confidence:result.confidence||0,summary:result.executive_summary||'',status:investigationStatus,anomalies:Number(result.metrics?.anomaly_count||0),evidenceCount:(result.evidence||[]).length,topHypothesis:result.likely_causes?.[0]?.cause||'—',actions:(result.next_actions||[]).slice(0,3),mode:result.mode||'baseline'};const idx=h.findIndex(x=>x.id===entry.id);if(idx>=0)h[idx]={...h[idx],...entry};else h.unshift(entry);localStorage.setItem(historyKey(),JSON.stringify(h.slice(0,20)))}
function renderWorkspace(){const h=getHistory();const selected=h.slice(0,10);const options=selected.map(x=>'<option value="'+esc(x.id)+'">'+esc(x.id)+' · '+esc(x.fileName||'untitled')+'</option>').join('');return '<section class="workspace-panel"><div class="workspace-head"><div><span class="step">00</span><div><h2>Investigation workspace</h2><p>Local case history · reports stay in this browser</p></div></div><div class="workspace-actions"><button id="clearHistory" class="tool-btn subtle">Clear local history</button></div></div><div class="workspace-grid"><div><div class="history-list">'+(selected.length?selected.map(x=>'<button class="history-card" data-history-id="'+esc(x.id)+'"><div><strong>'+esc(x.id)+'</strong><span>'+esc(x.fileName||'Untitled CSV')+'</span></div><div><b class="history-risk '+esc(String(x.risk).toLowerCase())+'">'+esc(x.risk)+'</b><em>'+esc(x.status)+'</em></div><small>'+esc(new Date(x.createdAt).toLocaleString())+'</small></button>').join(''):'<div class="empty-history">No saved investigations yet. Run an analysis to create the first case.</div>')+'</div></div>'+(selected.length>=2?'<div class="compare-box"><span class="preview-label">COMPARE TWO CASES</span><div class="compare-selects"><select id="compareA">'+options+'</select><select id="compareB">'+options+'</select></div><button id="compareBtn" class="tool-btn">Compare reports ›</button><div id="comparisonResult"></div></div>':'')+'</div></section>'}
async function saveServerEntry(){if(!result)return;try{await fetch('/api/investigations?id='+encodeURIComponent(investigationId),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:investigationId,createdAt:new Date().toISOString(),vehicle,fileName,status:investigationStatus,report:result})})}catch{}}
async function loadRemoteInvestigation(id){try{const res=await fetch('/api/investigations?id='+encodeURIComponent(id),{cache:'no-store'});const data=await res.json();if(!res.ok||!data.investigation)throw new Error(data.error||'Investigation not found');const x=data.investigation;investigationId=x.id;investigationStatus=x.status||'OPEN';vehicle=x.vehicle||vehicle;fileName=x.fileName||'';result=x.report||null;csvText='';error='';resetReplay();render();window.scrollTo({top:document.querySelector('.results')?.offsetTop||0,behavior:'smooth'})}catch(e){error=e?.message||'Shared investigation could not be loaded.';render()}}
function shareInvestigation(){const url=new URL(window.location.href);url.search='';url.searchParams.set('investigation',investigationId);navigator.clipboard?.writeText(url.toString()).then(()=>{const b=document.querySelector('#shareInvestigation');if(b){b.textContent='✓ Link copied';setTimeout(()=>b.textContent='↗ Share investigation',1400)}}).catch(()=>{window.prompt('Copy investigation link:',url.toString())})}
function loadHistoryEntry(id){const x=getHistory().find(v=>v.id===id);if(!x)return;investigationId=x.id;investigationStatus=x.status||'OPEN';fileName=x.fileName||'';vehicle=x.vehicle||vehicle;result={risk_level:x.risk,confidence:x.confidence,executive_summary:x.summary,metrics:{anomaly_count:x.anomalies},likely_causes:x.topHypothesis&&x.topHypothesis!=='—'?[{cause:x.topHypothesis,confidence:x.confidence,why:'Stored case summary; rerun the source CSV for full evidence.'}]:[],evidence:[],timeline:[],next_actions:x.actions||[],mode:x.mode||'baseline'};csvText='';render();window.scrollTo({top:document.querySelector('.results')?.offsetTop||0,behavior:'smooth'})}
function clearHistory(){if(!getHistory().length)return;if(confirm('Clear all locally saved AeroSage investigations?')){localStorage.removeItem(historyKey());render()}}
function renderComparison(){const a=getHistory().find(x=>x.id===document.querySelector('#compareA')?.value),b=getHistory().find(x=>x.id===document.querySelector('#compareB')?.value),out=document.querySelector('#comparisonResult');if(!a||!b||!out)return;out.innerHTML='<div class="comparison"><div><span>RISK</span><b>'+esc(a.risk)+'</b><b>'+esc(b.risk)+'</b></div><div><span>CONFIDENCE</span><b>'+Math.round(a.confidence*100)+'%</b><b>'+Math.round(b.confidence*100)+'%</b></div><div><span>ANOMALIES</span><b>'+a.anomalies+'</b><b>'+b.anomalies+'</b></div><div><span>EVIDENCE</span><b>'+a.evidenceCount+'</b><b>'+b.evidenceCount+'</b></div><div><span>TOP HYPOTHESIS</span><p>'+esc(a.topHypothesis)+'</p><p>'+esc(b.topHypothesis)+'</p></div></div>'}
async function checkSystem(){try{const r=await fetch('/api/analyze?action=health',{method:'GET',cache:'no-store'});const data=await r.json();systemStatus=r.ok&&data.status==='ok'?'operational':'degraded'}catch{systemStatus='unreachable'}render()}
checkSystem();
const sharedId=new URLSearchParams(window.location.search).get('investigation');
if(sharedId) loadRemoteInvestigation(sharedId);
