const app=document.querySelector('#app');
let csvText='', fileName='', vehicle='Parrot Anafi', notes='Investigate abnormal motor shutdowns, battery events and flight-control anomalies.', result=null, loading=false, error='';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function render(){
  app.innerHTML=`<div class="app-shell"><nav><div class="brand"><div class="brandmark">◉</div><span>AeroSage</span><em>AI</em></div><div class="nav-badges"><span>NEBIUS</span><span>NVIDIA NEMOTRON</span></div></nav><main>
  <section class="hero"><div class="eyebrow">✣ AI TELEMETRY INCIDENT INVESTIGATOR</div><h1>Turn machine logs into<br><span>evidence you can act on.</span></h1><p>AeroSage profiles telemetry, detects anomalies, reconstructs incident sequences and enriches the evidence with Nemotron and Tavily without allowing provider failures to erase the forensic report.</p></section>
  <section class="workspace"><div class="panel upload-panel"><div class="panel-head"><div><span class="step">01</span><h2>Evidence intake</h2></div><span>♢</span></div>
  <label class="dropzone"><input id="fileInput" type="file" accept=".csv,text/csv"><strong>${fileName?esc(fileName):'Drop a telemetry CSV'}</strong><small>${fileName?`${(csvText.length/1024).toFixed(1)} KB loaded locally`:'CSV · max 4 MB for this MVP'}</small></label>
  <button id="demoBtn" class="ghost">Load real sanitized drone incident demo ›</button>
  <div class="field-grid"><label>Vehicle / system<input id="vehicle" value="${esc(vehicle)}"></label><label>Investigation goal<textarea id="notes" rows="3">${esc(notes)}</textarea></label></div>
  <button id="runBtn" class="primary" ${!csvText||loading?'disabled':''}>${loading?'⌁ Investigating telemetry…':'✣ Run forensic analysis'}</button>${error?`<div class="error">ⓧ ${esc(error)}</div>`:''}</div>
  <div class="panel process-panel"><div class="panel-head"><div><span class="step">02</span><h2>Investigation pipeline</h2></div></div><div class="pipeline">
  ${proc('◔','Schema profiler','Discovers numeric signals, ranges and missingness without assuming one drone vendor.')}${proc('△','Anomaly engine','Flags robust statistical outliers plus domain safety events such as cut-outs and critical battery states.')}${proc('✣','Nemotron reasoning','Ranks competing hypotheses from evidence rather than inventing a single cause.')}${proc('♢','Evidence guardrails','Post-validates every AI hypothesis against target-event telemetry before it can be ranked.')}${proc('⌕','Technical grounding','Uses Tavily to compare the incident against manuals and documented failure modes when available.')}</div><div class="privacy"><span>♢</span><div><strong>Evidence-first by design</strong><span>The baseline report is returned before any external AI call.</span></div></div></div></section>
  ${result?renderResult(result):''}<footer><span>AeroSage · Nebius × NVIDIA Global AI Hackathon 2026</span><span>Standalone zero-dependency MVP · MIT</span></footer></main></div>`;
  bind();
}
function proc(icon,title,text){return `<div class="process"><div>${icon}</div><section><strong>${title}</strong><p>${text}</p></section></div>`}
function renderResult(r){const score=Math.round((r.confidence||0)*100);const status=r.mode==='live'?`Live Nemotron analysis · ${esc(r.model||'')}${r.web_status==='live'?' · Tavily grounded':''} · evidence-checked`:r.mode==='baseline'?'Evidence-first report ready · enriching with Nemotron + Tavily…':`Evidence-first report · Nemotron fallback${r.web_status==='live'?' · Tavily grounded':''}`;return `<section class="results"><div class="section-title"><span class="step">03</span><div><h2>Incident report</h2><p>${status}</p>${r.ai_note?`<p class="query">Nemotron note: ${esc(r.ai_note)}</p>`:''}</div></div>
<div class="summary-grid"><div class="panel verdict-card"><div class="verdict-top"><span class="risk ${esc(r.risk_level)}">${esc(r.risk_level)} risk</span><div class="confidence"><strong>${score}%</strong><span>confidence</span></div></div><h3>Investigator conclusion</h3><p>${esc(r.executive_summary)}</p><div class="metric-row">${metric(r.metrics?.rows,'records')}${metric(r.metrics?.numeric_columns,'signals')}${metric(r.metrics?.anomaly_count,'anomalies')}${metric(r.metrics?.incident_rows,'incident rows')}</div></div>
<div class="panel causes-card"><h3>Ranked hypotheses</h3><div class="causes">${(r.likely_causes||[]).map((c,i)=>`<div class="cause"><div class="cause-row"><span>${i+1}</span><strong>${esc(c.cause)}</strong><b>${Math.round((c.confidence||0)*100)}%</b></div><p>${esc(c.why)}</p><div class="bar"><i style="width:${Math.round((c.confidence||0)*100)}%"></i></div></div>`).join('')}</div></div></div>
<div class="detail-grid"><div class="panel"><h3>Evidence ledger</h3><div class="evidence-list">${(r.evidence||[]).map(e=>`<div class="evidence"><span class="dot ${esc(e.weight)}"></span><div><strong>${esc(e.signal)}</strong><p>${esc(e.observation)}</p></div><em>${esc(e.weight)}</em></div>`).join('')}</div></div><div class="panel"><h3>Reconstructed sequence</h3><div class="timeline">${(r.timeline||[]).map((t,i)=>`<div class="timeline-item"><span>${String(i+1).padStart(2,'0')}</span><div><strong>${esc(t.phase)}</strong><p>${esc(t.finding)}</p></div></div>`).join('')}</div></div></div>
<div class="panel actions"><h3>Recommended next actions</h3><div class="action-grid">${(r.next_actions||[]).map(a=>`<div><span>✓</span><span>${esc(a)}</span></div>`).join('')}</div></div>
${r.evidence_guardrails?.length?`<div class="panel"><h3>Evidence guardrails</h3><p class="query">AI proposes · telemetry decides${r.guardrail_filtered?` · ${r.guardrail_filtered} unsupported claim(s) filtered`:''}</p><div class="evidence-list">${r.evidence_guardrails.map(g=>`<div class="evidence"><span class="dot high"></span><div><strong>Constraint</strong><p>${esc(g)}</p></div><em>checked</em></div>`).join('')}</div></div>`:''}
${r.web_grounding?.sources?.length?`<div class="panel grounding"><h3>Technical grounding</h3><p class="query">Search: “${esc(r.web_grounding.query)}”</p><div class="sources">${r.web_grounding.sources.map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noreferrer"><span>⌕</span><span>${esc(s.title)}</span><span>›</span></a>`).join('')}</div></div>`:''}</section>`}
function metric(v,l){return `<div class="metric"><strong>${Number(v||0)}</strong><span>${l}</span></div>`}
function bind(){
  document.querySelector('#demoBtn')?.addEventListener('click',async()=>{error='';const r=await fetch('/demo/anafi_incidents_sanitized.csv');csvText=await r.text();fileName='anafi_incidents_sanitized.csv';vehicle='Parrot Anafi';notes='Investigate the motor cut-out sequence and distinguish it from battery, radio-link, GPS, or magnetic causes.';result=null;render()});
  document.querySelector('#fileInput')?.addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>4_000_000){error='For this MVP, use a CSV under 4 MB.';render();return}csvText=await f.text();fileName=f.name;result=null;error='';render()});
  document.querySelector('#vehicle')?.addEventListener('input',e=>vehicle=e.target.value);document.querySelector('#notes')?.addEventListener('input',e=>notes=e.target.value);
  document.querySelector('#runBtn')?.addEventListener('click',analyze);
}
async function parseResponse(res){const raw=await res.text();try{return JSON.parse(raw)}catch{return {error:`Backend returned unreadable data (HTTP ${res.status}).`}}}
async function call(action){const url=`/api/analyze?action=${encodeURIComponent(action)}&vehicle=${encodeURIComponent(vehicle)}&notes=${encodeURIComponent(notes)}`;const res=await fetch(url,{method:'POST',headers:{'content-type':'text/csv; charset=utf-8'},body:csvText});const data=await parseResponse(res);if(!res.ok||data.error)throw new Error(data.error||`HTTP ${res.status}`);return data}
async function analyze(){if(!csvText||loading)return;loading=true;error='';result=null;render();try{result=await call('base');loading=false;render();try{const enriched=await call('enrich');if(enriched&&!enriched.error)result=enriched}catch{}render()}catch(e){loading=false;error=e?.message||'Analysis failed';render()}}
render();
